#!/bin/bash

init=0
copy=0
force=0
script_name=$(basename "$0")

shopt -s nullglob
local_paths=($(realpath -e */))
shopt -u nullglob

if [ -n "${SUDO_USER}" ]; then
	HOME="/home/$SUDO_USER"
	# TO DO: scan all scripts for used env's and replace them
fi

Help()
{
	# Display Help
	echo "$script_name script will deploy config files according to their respective deployment scripts with either symlink or copy."
	echo
	echo "Syntax: deploy [options] [arg]"
	echo "options:"
	echo "h     Print this Help."
	echo "l     List available package configs."
	echo "c     Copy files instead of using symlinks."
	echo "i     Initialize dir name [arg] with script template."
	echo "f     Force files to replace existing."
	echo "x     Debug mode."
	echo
}

List()
{
	for local_path in "${local_paths[@]}"; do
		echo "$(basename $local_path)"
	done
}

Init()
{
	if [ "${#script_args[@]}" -eq 0 ]; then
		echo "Init requires arg. Run $script_name -h for more details."
		exit 1
	fi

	for arg in "${script_args[@]}"; do
		echo "Initializing: $arg"
		if ! [ -d ./$arg ] ; then
			echo "Creating $arg directory"
			mkdir ./$arg
		fi
		if [ -e ./$arg/deploy ] && [ ${force} -eq 0 ] ; then
			echo "Overwrite permission required to re-init $arg. Run $script_name -f."
			continue
		fi
		echo "Copying template -> $arg/deply"
		cp $cp_args ./template ./$arg/deploy
	done
}

Deploy()
{
	if [ "${#script_args[@]}" -gt 0 ]; then
		local_paths=( $(realpath -e "${script_args[@]}") )
	fi

	for local_path in "${local_paths[@]}"; do
		echo "Deploying: $dir"
		if [ -e "${local_path}/deploy" ] ; then
			source "${local_path}/deploy"
		else
			echo "(basename $local_path) deployment missing."
		fi
	done
}

#########################
# Arguments and options
#########################
while getopts ":hlcif" flag
do
	case "$flag" in
		h)
			Help 
			exit;;
		l) 
			List
			exit;;
		c) 
			copy=1;;
		i)
			init=1;;
		f)
			force=1;;
		x)
			set -x;;
		\?) 
			echo "$0: Error: Invalid option: -${OPTARG}" >&2; 
			exit 1;;
	esac
done
shift $((OPTIND - 1))
script_args=("$@")

##########################
# Construct $cp_args
##########################
cp_args="s"
if [ ${init} -eq 1 ] || [ ${copy} -eq 1 ] ; then 
	cp_args=""
fi
if [ ${force} -eq 1 ]; then
	cp_args="${cp_args}f"
fi
cp_args="-${cp_args}"

if [ ${#cp_args} -eq 1 ] ; then
	cp_args=""
fi
#echo "cp args: ${cp_args}"

#############
# Go Button
#############
if [ ${init} -eq 1 ] ; then
	Init
	exit
fi

Deploy
