#!/bin/bash

# TODO install ripgrep as telescope dependency

######################
# Deploy directories
######################
paths=(
	"$HOME/.config/nvim/"
)
nvim_config="$HOME/.config/"
if [ -d $HOME/.var/app/io.neovim.nvim ]; then
	paths=(
		"$HOME/.var/app/io.neovim.nvim/config/nvim/"
	)
  nvim_config="$HOME/.var/app/io.neovim.nvim/config/"
fi

for path in "${paths[@]}" ; do
  path=$(realpath -s $path)
	echo $path
  if [ -L $path ] ; then
    echo "Link exists"
    rm $path
    continue
  fi
	if [ -e $path ] && [ ! -L $path ] ; then
		echo "Dir exists"
    rm -rf $path
		continue
	fi
done

################
# Deploy files
################
ln -sf $local_path $nvim_config
