#!/bin/sh

if [ -z "$1" ]; then
  printf "Usage: %s /path/to/image\n" "$(basename $0)" >&2
  exit 1
fi

_set_awww() {
  awww img "$1" \
    --transition-type wipe
}

_set_nitrogen() {
  nitrogen --set-zoom-fill "$1" --save
}

_set_feh() {
  feh --bg-fill "$1"
}

# BG_ENGINE global set in .config/shell/wallpaper.sh
_bg_engine=$(systemctl --user show-environment | grep '^BG_ENGINE=' | cut -d= -f2)
case "$_bg_engine" in

awww) _set_awww "$1" ;;
nitrogen) _set_nitrogen "$1" ;;
feh) _set_feh "$1" ;;

*)
  printf "Error: BG_ENGINE not set or unsupported (%s)\n" "$BG_ENGINE" >&2
  exit 1
  ;;
esac
