# Default colors
[colors.primary]
background = '#14161b'
foreground = '#ebeef5'

[colors.cursor]
text = '#1c1d23'
cursor = '#ebeef5'

# Normal colors
[colors.normal]
# black   = '#14161b'
# red     = '#5e0009'
# green   = '#015825'
# yellow  = '#6e5600'
# blue    = '#005078'
# magenta = '#4c0049'
# cyan    = '#007676'
# white   = '#4f5258'
black   = '#9b9ea4'
red     = '#ffbcb5'
green   = '#aaedb7'
yellow  = '#f4d88c'
blue    = '#9fd8ff'
magenta = '#ffc3fa'
cyan    = '#83efef'
white   = '#9b9ea4'

# Bright colors
[colors.bright]
black   = '#14161b'
red     = '#5e0009'
green   = '#015825'
yellow  = '#6e5600'
blue    = '#005078'
magenta = '#4c0049'
cyan    = '#007676'
white   = '#4f5258'
# black   = '#9b9ea4'
# red     = '#ffbcb5'
# green   = '#aaedb7'
# yellow  = '#f4d88c'
# blue    = '#9fd8ff'
# magenta = '#ffc3fa'
# cyan    = '#83efef'
# white   = '#9b9ea4'

# Dark:
# blue    = "#005078"
# cyan    = "#007676"
# green   = "#015825"
# grey1   = "#0a0b10"
# grey2   = "#1c1d23"
# grey3   = "#2c2e33"
# grey4   = "#4f5258"
# magenta = "#4c0049"
# red     = "#5e0009"
# yellow  = "#6e5600"
#
# Light:
# blue    = "#9fd8ff"
# cyan    = "#83efef"
# green   = "#aaedb7"
# grey1   = "#ebeef5"
# grey2   = "#d7dae1"
# grey3   = "#c4c6cd"
# grey4   = "#9b9ea4"
# magenta = "#ffc3fa"
# red     = "#ffbcb5"
# yellow  = "#f4d88c"
