#!/bin/bash
##################
# Install stats
#################
# apt-cache policy <package-name>
# dpkg -l | grep -E '^ii | grep <package-name>
# which <package-name>
# test -e /usr/bin/<package-name>
# test -e /opt/???/<package-name>
# test -e /bin/<package-name>


######################
# Deploy directories
######################
paths=(
	"$HOME/.config/nvim"
)
if [ -d $HOME/.var/app/io.neovim.nvim ]; then
	paths=(
		"$HOME/.var/app/io.neovim.nvim/config/nvim"
	)
fi

for path in "${paths[@]}" ; do
	echo $path
	if [ -e $path ] ; then
		echo "dir exists"
		continue
	fi
	mkdir -p $dir
done

################
# Deploy files
################
cp $cp_args $local_path/init.lua "$HOME/.var/app/io.neovim.nvim/config/nvim"
#cp $cp_args
