#!/bin/bash
################
# Deploy files
################
cp $cp_args "$local_path/aliases" "$HOME/.bash_aliases"
cp $cp_args "$local_path/bashrc" "$HOME/.bashrc"
cp $cp_args "$local_path/bash_logout" "$HOME/.bash_logout"
cp $cp_args "$local_path/profile" "$HOME/.profile"
cp $cp_args "$local_path/dircolors" "$HOME/.dircolors"
