alias media="cd '/media/user/4TB HDD'"
alias cls="clear"
alias vim="flatpak run io.neovim.nvim"
alias clip="xclip -sel clip"
alias aliases="/home/user/.bash_aliases"
alias dotfiles="sudo ansible-pull -U https://github.com/gtrcoi/dotfiles_ansible.git"
alias gits="git status"
