#!/bin/bash
################
# Deploy files
################
cp $cp_args "$local_path/.bash_aliases" "$HOME"
cp $cp_args "$local_path/.bashrc" "$HOME"
cp $cp_args "$local_path/.bash_logout" "$HOME"
cp $cp_args "$local_path/.profile" "$HOME"
